#!/usr/bin/env python3

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GLib, Pango, Gio
import subprocess
import os
import threading

PROJECT_DIR = os.path.dirname(os.path.realpath(__file__))
HOTSPOT_BIN = os.path.join(PROJECT_DIR, "wifi-hotspot")

class HotspotGUI(Gtk.ApplicationWindow):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.set_default_size(500, 550)
        self.set_position(Gtk.WindowPosition.CENTER)
        
        hb = Gtk.HeaderBar()
        hb.set_show_close_button(True)
        hb.props.title = "Fedora Wi-Fi Hotspot"
        self.set_titlebar(hb)
        
        self.main_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=15)
        self.main_box.set_margin_top(20)
        self.main_box.set_margin_bottom(20)
        self.main_box.set_margin_start(30)
        self.main_box.set_margin_end(30)
        self.add(self.main_box)
        
        self.status_icon = Gtk.Image.new_from_icon_name("network-wireless-disconnected-symbolic", Gtk.IconSize.DIALOG)
        self.status_icon.set_pixel_size(64)
        self.main_box.pack_start(self.status_icon, False, False, 0)
        
        self.status_label = Gtk.Label(label="Hotspot is Off")
        self.status_label.modify_font(Pango.FontDescription("sans bold 16"))
        self.main_box.pack_start(self.status_label, False, False, 0)
        
        switch_box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        switch_box.set_halign(Gtk.Align.CENTER)
        self.toggle_switch = Gtk.Switch()
        self.toggle_switch.set_size_request(60, -1)
        self.toggle_switch.connect("notify::active", self.on_switch_activated)
        switch_box.pack_start(self.toggle_switch, False, False, 0)
        self.main_box.pack_start(switch_box, False, False, 10)
        
        settings_frame = Gtk.Frame()
        self.main_box.pack_start(settings_frame, False, False, 0)
        
        grid = Gtk.Grid(row_spacing=10, column_spacing=15)
        grid.set_margin_top(15)
        grid.set_margin_bottom(15)
        grid.set_margin_start(15)
        grid.set_margin_end(15)
        settings_frame.add(grid)
        
        lbl_ssid = Gtk.Label(label="Network Name:")
        lbl_ssid.set_halign(Gtk.Align.END)
        self.entry_ssid = Gtk.Entry()
        self.entry_ssid.set_text("hareram")
        self.entry_ssid.set_hexpand(True)
        grid.attach(lbl_ssid, 0, 0, 1, 1)
        grid.attach(self.entry_ssid, 1, 0, 1, 1)
        
        lbl_pwd = Gtk.Label(label="Password:")
        lbl_pwd.set_halign(Gtk.Align.END)
        self.entry_pwd = Gtk.Entry()
        self.entry_pwd.set_text("12345678")
        self.entry_pwd.set_visibility(False)
        self.entry_pwd.set_input_purpose(Gtk.InputPurpose.PASSWORD)
        grid.attach(lbl_pwd, 0, 1, 1, 1)
        grid.attach(self.entry_pwd, 1, 1, 1, 1)

        self.check_show_pwd = Gtk.CheckButton(label="Show Password")
        self.check_show_pwd.connect("toggled", self.on_show_pwd_toggled)
        grid.attach(self.check_show_pwd, 1, 2, 1, 1)

        self.btn_refresh = Gtk.Button(label="Refresh Connected Devices")
        self.btn_refresh.connect("clicked", self.on_refresh_clicked)
        self.btn_refresh.set_sensitive(False)
        self.main_box.pack_start(self.btn_refresh, False, False, 0)
        
        self.textview = Gtk.TextView()
        self.textview.set_editable(False)
        self.textview.set_wrap_mode(Gtk.WrapMode.WORD)
        self.textview.modify_font(Pango.FontDescription("monospace 10"))
        
        scroll = Gtk.ScrolledWindow()
        scroll.set_vexpand(True)
        scroll.add(self.textview)
        self.main_box.pack_start(scroll, True, True, 0)

        self.is_running = False

    def on_show_pwd_toggled(self, button):
        self.entry_pwd.set_visibility(button.get_active())

    def append_output(self, text):
        buffer = self.textview.get_buffer()
        end_iter = buffer.get_end_iter()
        buffer.insert(end_iter, text + "\n")
        mark = buffer.create_mark(None, buffer.get_end_iter(), False)
        self.textview.scroll_to_mark(mark, 0.05, True, 0.0, 1.0)
        
    def set_ui_state(self, is_active):
        self.is_running = is_active
        # Only update the switch if it doesn't match the current state, avoiding recursive signals
        if self.toggle_switch.get_active() != is_active:
            self.toggle_switch.set_state(is_active)
            
        if is_active:
            self.status_icon.set_from_icon_name("network-wireless-signal-excellent-symbolic", Gtk.IconSize.DIALOG)
            self.status_label.set_text("Hotspot is Active")
            self.entry_ssid.set_sensitive(False)
            self.entry_pwd.set_sensitive(False)
            self.btn_refresh.set_sensitive(True)
        else:
            self.status_icon.set_from_icon_name("network-wireless-disconnected-symbolic", Gtk.IconSize.DIALOG)
            self.status_label.set_text("Hotspot is Off")
            self.entry_ssid.set_sensitive(True)
            self.entry_pwd.set_sensitive(True)
            self.btn_refresh.set_sensitive(False)

    def on_switch_activated(self, switch, gparam):
        if switch.get_active() and not self.is_running:
            self.start_hotspot()
        elif not switch.get_active() and self.is_running:
            self.stop_hotspot()
            
    def start_hotspot(self):
        ssid = self.entry_ssid.get_text().strip()
        pwd = self.entry_pwd.get_text().strip()
        if not ssid or not pwd:
            self.append_output("Error: SSID and Password cannot be empty.")
            self.toggle_switch.set_state(False)
            return
            
        cmd = ["sudo", HOTSPOT_BIN, "start", "--ssid", ssid, "--password", pwd]
        self.run_command_async(cmd, starting=True)

    def stop_hotspot(self):
        cmd = ["sudo", HOTSPOT_BIN, "stop"]
        self.run_command_async(cmd, starting=False)
        
    def on_refresh_clicked(self, widget):
        cmd = ["sudo", HOTSPOT_BIN, "status"]
        self.run_command_async(cmd, starting=self.is_running, refresh_only=True)

    def run_command_async(self, cmd, starting, refresh_only=False):
        self.toggle_switch.set_sensitive(False)
        self.btn_refresh.set_sensitive(False)
        
        if not refresh_only:
            self.textview.get_buffer().set_text("")
            
        self.append_output(f"Executing: {' '.join(cmd)}")
        
        def run():
            try:
                # Use pkexec if sudo requires a password in GUI, but we configure sudoers to avoid this
                process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True)
                for line in process.stdout:
                    GLib.idle_add(self.append_output, line.strip('\n'))
                process.wait()
                if not refresh_only:
                    if process.returncode == 0:
                        GLib.idle_add(self.set_ui_state, starting)
                    else:
                        GLib.idle_add(self.set_ui_state, False)
                        GLib.idle_add(self.toggle_switch.set_state, False)
                else:
                    GLib.idle_add(self.btn_refresh.set_sensitive, True)
                    
            except Exception as e:
                GLib.idle_add(self.append_output, f"Error: {e}")
                if not refresh_only:
                    GLib.idle_add(self.set_ui_state, False)
                    GLib.idle_add(self.toggle_switch.set_state, False)
            finally:
                GLib.idle_add(self.toggle_switch.set_sensitive, True)
                
        threading.Thread(target=run, daemon=True).start()

class HotspotApp(Gtk.Application):
    def __init__(self):
        super().__init__(application_id="com.github.fedorawifihotspot", flags=Gio.ApplicationFlags.FLAGS_NONE)
        
    def do_activate(self):
        win = self.props.active_window
        if not win:
            win = HotspotGUI(application=self)
        win.show_all()
        win.present()

if __name__ == "__main__":
    app = HotspotApp()
    app.run(None)
